### ISSUE TITLE
Downed site

### ISSUE THREAD

**Issue by ghost** [koenhendriks/YifyAPI#6] opened 2018-01-22 08:41 UTC
First of all, **I love your program.**
Is there a way to add something to abort, maybe not show an error when/if the site is down? I just started getting this error, this morning.

Warning: file_get_contents(): Peer certificate CN=`ssl371477.cloudflaressl.com' did not match expected CN=`yts.am' in /home/hev/www/www250/inc/YTS.php on line 195

Warning: file_get_contents(): Failed to enable crypto in /home/hev/www/www250/inc/YTS.php on line 195

Warning: file_get_contents(https://yts.am/api/v2/movie_details.json?movie_id=5&with_images&with_cast=): failed to open stream: operation failed in /home/hev/www/www250/inc/YTS.php on line 195

Fatal error: Uncaught Exception: HTTP request failed. Error was: file_get_contents(https://yts.am/api/v2/movie_details.json?movie_id=5&amp;with_images&amp;with_cast=): failed to open stream: operation failed in /home/hev/www/www250/inc/YTS.php:198 Stack trace: #0 /home/hev/www/www250/inc/YTS.php(72): YTS->getFromApi('https://yts.am/...') #1 /home/hev/www/www250/movie_details.php(257): YTS->movieDetail('5', false) #2 {main} thrown in /home/hev/www/www250/inc/YTS.php on line 198

**Comment by koenhendriks** [comment] 2018-08-13 22:55
Duplicate of #7

**Closed as completed by koenhendriks** 2018-08-13 22:55 UTC
